version: '3'
services:
  server:
    build: ./server
    ports:
      - "5001:5000"
    env_file:
      - .env
  client:
    build: ./client
    stdin_open: true
    tty: true
    depends_on:
      - server